name: llmengine-ci
on:
  push:
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y ninja-build build-essential libssl-dev
      - name: Configure
        run: cmake --preset debug
      - name: Build
        run: cmake --build build -j20
      - name: Test
        run: ctest --preset ctest-debug

