name: Docs (Doxygen)

on:
  workflow_dispatch:

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate docs
        run: |
          cmake --preset release
          cmake --build build --target docs --parallel 2

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: docs/html


